# Generated by Django 5.2.1 on 2025-09-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.area')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pos_data', serialize=False, to='games.gameitem')),
                ('sentence', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='punctuation_data', serialize=False, to='games.gameitem')),
                ('sentence', models.TextField()),
                ('hint', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpellingItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spelling_data', serialize=False, to='games.gameitem')),
                ('word', models.CharField(max_length=100)),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pos_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='games.partsofspeechitem')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('pos_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.partsofspeechitem')),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('mark', models.CharField(max_length=5)),
                ('punctuation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.punctuationitem')),
            ],
        ),
    ]
