# Generated by Django 5.2.1 on 2025-09-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsofspeechoption',
            name='pos_item',
        ),
        migrations.AddField(
            model_name='partsofspeechoption',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.partsofspeechword'),
            preserve_default=False,
        ),
    ]
