# Generated by Django 5.2.8 on 2025-11-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_grammaritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SELECT', 'Select'), ('ASSIST', 'Assist')], max_length=10)),
                ('question', models.TextField()),
                ('order_index', models.IntegerField()),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentChallengeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('image_src', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_src', models.CharField(blank=True, max_length=500, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.assessmentchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Area Assessment', max_length=255)),
                ('order_index', models.IntegerField(default=999)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='games.area')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentchallenge',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='games.assessmentlesson'),
        ),
        migrations.CreateModel(
            name='AssessmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.area')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.assessmentchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
