# Generated by Django 5.2.1 on 2025-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_partsofspeechoption_pos_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsofspeechword',
            name='correct_answer',
            field=models.CharField(default='Pangngalan', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartsOfSpeechOption',
        ),
    ]
