# Generated by Django 5.2.8 on 2025-11-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_assessmentchallenge_assessmentchallengeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprogress',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentprogress',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
