# Generated by Django 5.2.1 on 2025-09-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_partsofspeechword_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiSentenceItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emoji_data', serialize=False, to='games.gameitem')),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FourPicsOneWordItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fourpics_data', serialize=False, to='games.gameitem')),
                ('answer', models.CharField(max_length=100)),
                ('hint', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmojiSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=100)),
                ('emoji_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='games.emojisentenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='FourPicsOneWordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('fourpics_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.fourpicsoneworditem')),
            ],
        ),
    ]
