# Generated by Django 5.2.8 on 2025-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_assessmentprogress_passed_assessmentprogress_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentchallenge',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentchallenge',
            name='image_prompt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessmentchallengeoption',
            name='order_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentchallengeoption',
            name='pos_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentchallengeoption',
            name='word_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentchallenge',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select'), ('ASSIST', 'Assist'), ('SPELL', 'Spell'), ('PUNCTUATE', 'Punctuate'), ('ARRANGE', 'Arrange'), ('COMPOSE', 'Compose'), ('TAG_POS', 'Tag Parts of Speech')], max_length=15),
        ),
    ]
