# Generated by Django 5.2.1 on 2025-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gameroom_gameplayer_gameround_sentencecontribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['order_index'], 'verbose_name_plural': 'Areas'},
        ),
        migrations.AddField(
            model_name='area',
            name='game_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='area',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
