# Generated by Django 5.2.1 on 2025-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_area_options_area_game_type_area_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='game_type',
        ),
        migrations.AddField(
            model_name='area',
            name='theme_color',
            field=models.CharField(default='#4A90E2', max_length=7),
        ),
    ]
