# Generated by Django 5.2.1 on 2025-10-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_area_game_type_area_theme_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order_index']},
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, choices=[('spelling', 'Spelling'), ('punctuation', 'Punctuation'), ('parts_of_speech', 'Parts of Speech'), ('four_pics', '4 Pics 1 Word'), ('emoji', 'Emoji Sentence'), ('grammar', 'Grammar')], max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
