# Generated by Django 5.2.1 on 2025-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_options_game_game_type_game_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, choices=[('spelling-challenge', 'Spelling'), ('punctuation-task', 'Punctuation'), ('parts-of-speech', 'Parts of Speech'), ('word-association', '4 Pics 1 Word'), ('emoji-challenge', 'Emoji Sentence'), ('grammar-check', 'Grammar')], max_length=50),
        ),
    ]
