# Generated by Django 5.2.1 on 2025-10-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, choices=[('spelling-challenge', 'Spelling Challenge'), ('punctuation-task', 'Punctuation Task'), ('parts-of-speech', 'Parts of Speech'), ('word-association', 'Word Association'), ('emoji-challenge', 'Emoji Challenge'), ('grammar-check', 'Grammar Check')], max_length=50),
        ),
    ]
