# Generated by Django 5.2.1 on 2025-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.CharField(blank=True, choices=[('/images/bear.png', 'Avatar 1'), ('/images/cat.png', 'Avatar 2'), ('/images/chicken.png', 'Avatar 3'), ('/images/owl.png', 'Avatar 4'), ('/images/panda.png', 'Avatar 5'), ('/images/meerkat.png', 'Default')], max_length=255),
        ),
    ]
