# Generated by Django 5.2.1 on 2025-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
