# Generated by Django 5.2.1 on 2025-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroom_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(default='A', max_length=255),
        ),
    ]
