# Generated by Django 5.2.1 on 2025-06-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_alter_student_user_activity_pendingrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgameprogress',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentClassroomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stats', to='api.classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_stats', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
