# Generated by Django 5.2.1 on 2025-06-29 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentgameprogress_rank_studentclassroomstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(default=datetime.date.today, help_text='Deadline for the activity (YYYY-MM-DD HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='number_of_submissions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft')], default='Active', max_length=50),
        ),
    ]
