# Generated by Django 5.2.1 on 2025-07-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_date_joined'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPicsOneWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrammarGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartsOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PunctuationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(unique=True)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('complexity', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('mechanics', 'Mechanics'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('sentence_structure', 'Sentence Construction')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentgameprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentgameprogress',
            name='content_type',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgameprogress',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft')], default='active', max_length=50),
        ),
        migrations.CreateModel(
            name='PunctuationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.punctuationtask')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceConstructionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sentenceconstruction')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank')),
            ],
        ),
        migrations.CreateModel(
            name='SpellingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.spellinggame')),
                ('correct_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_correct_items', to='api.wordbank')),
                ('incorrect_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_incorrect_items', to='api.wordbank')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfSpeechItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.partsofspeech')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.grammargame')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank')),
                ('correct_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank')),
            ],
        ),
        migrations.CreateModel(
            name='FourPicsOneWordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='game_images/')),
                ('image2', models.ImageField(upload_to='game_images/')),
                ('image3', models.ImageField(upload_to='game_images/')),
                ('image4', models.ImageField(upload_to='game_images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.fourpicsoneword')),
                ('correct_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank')),
            ],
        ),
        migrations.CreateModel(
            name='WordMatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.wordmatching')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank')),
                ('word1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch1_items', to='api.wordbank')),
                ('word2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch2_items', to='api.wordbank')),
                ('word3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch3_items', to='api.wordbank')),
                ('word4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch4_items', to='api.wordbank')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentgameprogress',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
