# Generated by Django 5.2.1 on 2025-07-23 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fourpicsoneword_grammargame_partsofspeech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='rubric',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Time limit to complete the activity once started (e.g., 1:00:00 for 1 hour)'),
        ),
    ]
