# Generated by Django 5.2.1 on 2025-07-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activity_content_type_activity_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellingitem',
            name='incorrect_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_incorrect_items', to='api.wordbank'),
        ),
    ]
