# Generated by Django 5.2.1 on 2025-07-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_spellingitem_incorrect_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentenceBank',
            new_name='SentencesBank',
        ),
        migrations.RenameModel(
            old_name='WordBank',
            new_name='WordsBank',
        ),
    ]
