# Generated by Django 5.2.1 on 2025-07-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_sentencebank_sentencesbank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(unique=True)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('complexity', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='grammaritem',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank'),
        ),
        migrations.AlterField(
            model_name='partsofspeechitem',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank'),
        ),
        migrations.AlterField(
            model_name='punctuationitem',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank'),
        ),
        migrations.AlterField(
            model_name='sentenceconstructionitem',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank'),
        ),
        migrations.AlterField(
            model_name='wordmatchingitem',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sentencebank'),
        ),
        migrations.AlterField(
            model_name='fourpicsoneworditem',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='grammaritem',
            name='correct_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='partsofspeechitem',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='spellingitem',
            name='correct_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_correct_items', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='spellingitem',
            name='incorrect_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_incorrect_items', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='wordmatchingitem',
            name='word1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch1_items', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='wordmatchingitem',
            name='word2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch2_items', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='wordmatchingitem',
            name='word3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch3_items', to='api.wordbank'),
        ),
        migrations.AlterField(
            model_name='wordmatchingitem',
            name='word4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordmatch4_items', to='api.wordbank'),
        ),
        migrations.DeleteModel(
            name='SentencesBank',
        ),
        migrations.DeleteModel(
            name='WordsBank',
        ),
    ]
