# Generated by Django 5.2.1 on 2025-07-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sentencebank_wordbank_alter_grammaritem_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgameprogress',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='studentgameprogress',
            table='api_studentgameprogress',
        ),
    ]
