# Generated by Django 5.2.1 on 2025-07-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_studentgameprogress_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencebank',
            name='topic',
        ),
        migrations.AddField(
            model_name='sentencebank',
            name='word',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
