# Generated by Django 5.2.1 on 2025-07-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_sentencebank_topic_sentencebank_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencebank',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
