# Generated by Django 5.2.1 on 2025-07-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sentencebank_part_of_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsofspeechitem',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='partsofspeechitem',
            name='word',
        ),
    ]
