# Generated by Django 5.2.8 on 2025-12-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='gameprogress',
            name='score',
        ),
    ]
