# Generated by Django 5.2.1 on 2025-10-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rooms_played', models.PositiveIntegerField(default=0)),
                ('total_rounds_played', models.PositiveIntegerField(default=0)),
                ('average_sentence_score', models.FloatField(default=0.0)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
