# Generated by Django 5.2.8 on 2025-12-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_gameprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='difficulty_1_time_taken',
            field=models.FloatField(default=0.0, help_text='Time in seconds'),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='difficulty_2_time_taken',
            field=models.FloatField(default=0.0, help_text='Time in seconds'),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='difficulty_3_time_taken',
            field=models.FloatField(default=0.0, help_text='Time in seconds'),
        ),
    ]
