# Generated by Django 5.2.8 on 2025-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_gameprogress_difficulty_1_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprogress',
            name='difficulty_1_time_taken',
            field=models.FloatField(blank=True, default=0.0, help_text='Time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='difficulty_2_time_taken',
            field=models.FloatField(blank=True, default=0.0, help_text='Time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='difficulty_3_time_taken',
            field=models.FloatField(blank=True, default=0.0, help_text='Time in seconds', null=True),
        ),
    ]
