# Generated by Django 5.2.8 on 2025-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collected_badges',
            field=models.JSONField(blank=True, default=list, help_text='List of collected badge identifiers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ls_points',
            field=models.IntegerField(default=0),
        ),
    ]
