# Generated by Django 5.2.8 on 2025-12-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_collected_badges_and_more'),
        ('users', '0006_customuser_collected_badges'),
    ]

    operations = [
    ]
