# Generated by Django 5.2.8 on 2025-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20251212_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_hearts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='next_refill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
