# Generated by Django 5.2.8 on 2025-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_current_hearts_customuser_next_refill_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
